### ISSUE TITLE
Lambda Execution Timeout Setting

### ISSUE THREAD

**Issue by jmscholen** [nullstone-io/nullstone#90]
## Summary
When creating a lambda function on Nullstone, the default setting that is created is 3 secs before the function will timeout. I have a report function that is taking longer. 

## Intended Outcome
Add a setting for timeout execution of a function. 

## How will it work?
In the Configuration Settings, add a setting for function execution timeout.

**Comment by BSick7** [comment]
This currently exists in the Lambda service as the `service_timeout` variable.
See https://github.com/nullstone-modules/aws-lambda-service/blob/main/variables.tf#L22-L29
